function Structure_Diagram = Diagram(Structure)
%Input a Structure and a diagram of the truss is output
Structure_Diagram = figure;
axis([0 23 0 23])
hold on
for i = 1:length(Structure.Members)
    if isa(Structure.Members(i),'Member')
        if Structure.Members(i).Length < 3 | Structure.Members(i).SF_Yielding < 1 | Structure.Members(i).SF_Buckling < 1 ...
            | Structure.Members(i).SF_Shear < 1
            plot([Structure.Members(i).Start_Joint.Coordinate(1) Structure.Members(i).End_Joint.Coordinate(1)],...
            [Structure.Members(i).Start_Joint.Coordinate(2) Structure.Members(i).End_Joint.Coordinate(2)],'r')
        else
            if abs(Structure.Members(i).Internal_Force) < 1
                plot([Structure.Members(i).Start_Joint.Coordinate(1) Structure.Members(i).End_Joint.Coordinate(1)],...
                [Structure.Members(i).Start_Joint.Coordinate(2) Structure.Members(i).End_Joint.Coordinate(2)],'m')
            else
                plot([Structure.Members(i).Start_Joint.Coordinate(1) Structure.Members(i).End_Joint.Coordinate(1)],...
                [Structure.Members(i).Start_Joint.Coordinate(2) Structure.Members(i).End_Joint.Coordinate(2)],'k')
            end
        end
    end
end
for i = 1:length(Structure.Joints)
    if isa(Structure.Joints(i), 'Joint')
        if ~isempty(Structure.Joints(i).External_Force)
            plot([Structure.Joints(i).Coordinate(1) ...
                Structure.Joints(i).Coordinate(1)+(Structure.Joints(i).External_Force(1)/...
                norm(Structure.Joints(i).External_Force))],...
                [Structure.Joints(i).Coordinate(2) ...
                Structure.Joints(i).Coordinate(2)+(Structure.Joints(i).External_Force(2)/...
                norm(Structure.Joints(i).External_Force))], 'r:')
        elseif ~isempty(Structure.Joints(i).Reaction_Force)
            plot([Structure.Joints(i).Coordinate(1) ...
                Structure.Joints(i).Coordinate(1)+(Structure.Joints(i).Reaction_Force(1)/...
                norm(Structure.Joints(i).Reaction_Force))], ...
                [Structure.Joints(i).Coordinate(2) ...
                Structure.Joints(i).Coordinate(2)+(Structure.Joints(i).Reaction_Force(2)/...
                norm(Structure.Joints(i).Reaction_Force))], 'g--')
        end
    end
end
end


